name: Dummy build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '01 01 * * 6'    # Run every Saturday

jobs:
#
#   list-linux:
#     name: set perl version for linux
#     runs-on: linux-latest
#     steps:
#       - uses: shogo82148/actions-setup-perl@v1
#       - id: set-matrix
#         name: list available perl versions
#         shell: perl {0}
#         run: |
#           use Actions::Core;
#           set_output(matrix => {perl => ['5.42.0']});
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}
#
#   run-linux:
#     runs-on: linux-latest
#     needs: list-linux
#     strategy:
#       fail-fast: false
#       matrix: ${{fromJson(needs.list.outputs.matrix)}}
#     steps:
#       - uses: actions/checkout@v6
#       - name: Setup perl
#         uses: shogo82148/actions-setup-perl@v1
#         with:
#           perl-version: ${{ matrix.perl }}
#       - name: Perl version
#         run: perl -V


#   list-macos:
#     name: list available perl versions
#     runs-on: macos-latest
#     steps:
#       - uses: shogo82148/actions-setup-perl@v1
#       - id: set-matrix
#         name: list available perl versions
#         shell: perl {0}
#         run: |
#           use Actions::Core;
#
#           print "Version available\n";
#           my @versions = grep { ! /^5\.6\./ } perl_versions();
#           for my $v (@versions) {
#             print "\t$v\n";
#           }
#           # Don't want anything less then 5.8
#           @versions = grep { ! /^5\.6\.*/ } @versions;
#           @versions = '5.42.0';
#           set_output(matrix => {perl => [@versions]});
#     outputs:
#       matrix: ${{ steps.set-matrix.outputs.matrix }}
#
#   run-macos:
#     runs-on: macos-latest
#     needs: list-macos
#     strategy:
#       fail-fast: false
#       matrix: ${{fromJson(needs.list-macos.outputs.matrix)}}
#     steps:
#       - uses: actions/checkout@v6
#       - name: Setup perl
#         uses: shogo82148/actions-setup-perl@v1
#         with:
#           perl-version: ${{ matrix.perl }}
#       - name: Perl version
#         run: perl -V
#     #   - name: Install dependencies
#     #     run: cpanm --quiet --installdeps --notest .
#     #   - name: Build
#     #     run: perl Makefile.PL && make
#     #   - name: Test
#     #     run: make test



  list-windows-default:
    name: perl versions for windows default
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Default Version available\n";
          my @default_versions = perl_versions();
          for my $v (@default_versions) {
            print "\t$v\n";
          }
          # Don't want anything less then 5.8
          @default_versions = grep { ! /^5\.6\.*/ } @default_versions;
          @default_versions = ('5.42.0');

          set_output(matrix => {perl => [@default_versions],    distribution => ['default'] });
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}


  list-windows-strawberry:
    name: perl version for windows strawberry
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          print "Strawberry Version available\n";
          my @strawberry_versions = perl_versions();
          for my $v (@strawberry_versions) {
            print "\t$v\n";
          }
          # Don't want anything less then 5.8
          @strawberry_versions = grep { ! /^5\.6\.*/ } @strawberry_versions;
          @strawberry_versions = ('5.42.0');

          set_output(matrix => {perl => [@strawberry_versions], distribution => ['strawberry'] });
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run-windows:
    name: Perl ${{ matrix.perl }} on '${{ matrix.distribution }}'
    runs-on: windows-latest
    needs: [list-windows-default, list-windows-strawberry]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.list-windows-default.outputs.matrix )}} ${{ fromJson(needs.list-windows-strawberry.outputs.matrix )}}
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.distribution }}
      - name: Install packages
        run: choco install make
      - name: Perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .
      - name: Build
        run: perl Makefile.PL && make
      - name: Test
        run: make test


#
#   run-windows-strawberry:
#     name: Perl ${{ matrix.perl }} on '${{ matrix.distribution }}'
#     runs-on: windows-latest
#     needs: list-windows-strawberry
#     strategy:
#       fail-fast: false
#       matrix: ${{fromJson(needs.list-windows-strawberry.outputs.matrix)}}
#     steps:
#       - uses: actions/checkout@v6
#       - name: Setup perl
#         uses: shogo82148/actions-setup-perl@v1
#         with:
#           perl-version: ${{ matrix.perl }}
#           distribution: ${{ matrix.distribution }}
#       - name: Install packages
#         run: choco install make
#       - name: Perl version
#         run: perl -V
#       - name: Install dependencies
#         run: cpanm --quiet --installdeps --notest .
#       - name: Build
#         run: perl Makefile.PL && make
#       - name: Test
#         run: make test