name: Windows build

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    - cron: '01 01 * * 6'    # Run every Saturday

jobs:

  list-default:
    name: list available default perl versions
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          my @versions = perl_versions();

          print "Default Perl Versions available\n";
          for my $v (@versions) {
            print "\t$v\n";
          }

          # Don't want anything less then 5.8
          @versions = grep { ! /5\.6\.*/ } @versions;

          set_output(matrix => { perl => [@versions], distribution => ['default']});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}


  list-strawberry:
    name: list available strawberry perl versions
    runs-on: windows-latest
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available strawberry perl versions
        shell: perl {0}
        run: |
          use Actions::Core;

          my @versions = perl_versions(platform => 'win32', distribution => 'strawberry');

          print "Strawberry Versions Available\n";
          for my $v (@versions) {
            print "\t$v\n";
            }

          # Don't want anything less then 5.8
          @versions = grep { ! /5\.6\.*/ } @versions;

          set_output(matrix => { perl => [@versions], distribution => ['strawberry']});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run:
    runs-on: windows-latest
    needs: [list-default]
    # needs: [list-default, list-strawberry]
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.list.outputs.matrix)}}
    name: Perl ${{ matrix.perl }} with '${{ matrix.distribution }}' distribution
    steps:
      - uses: actions/checkout@v6
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ matrix.distribution }}
      - name: Install packages
        run: choco install make
      - name: Perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --quiet --installdeps --notest .
      - name: Build
        run: perl Makefile.PL && make
      - name: Test
        run: make test



  # run-strawberry:
  #   runs-on: windows-latest
  #   needs: list
  #   strategy:
  #     fail-fast: false
  #     matrix: ${{fromJson(needs.list.outputs.matrix)}}
  #   name: Perl ${{ matrix.perl }} with '{{ matrix.distribution }}' distribution
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Setup perl
  #       uses: shogo82148/actions-setup-perl@v1
  #       with:
  #         perl-version: ${{ matrix.perl }}
  #         distribution: ${{ matrix.distribution }}
  #     - name: Install packages
  #       run: choco install make
  #     - name: Perl version
  #       run: perl -V
  #     - name: Install dependencies
  #       run: cpanm --quiet --installdeps --notest .
  #     - name: Build
  #       run: perl Makefile.PL && make
  #     - name: Test
  #       run: make test
